---
ssh_public_keys_dir: ../../extra/ssh_public_keys

manala_accounts_groups:
  - group: devops
    system: false
  - group: restricted_user
    system: false

manala_accounts_users:
  - user: root
    authorized_keys:
      - "{{ ssh_public_keys_dir }}/example_user.pub"
  - user: deploy
    groups: ['restricted_user']
    authorized_keys:
      - "{{ ssh_public_keys_dir }}/example_user.pub"
  - user: devops
    groups: ['devops', 'sudo']
    authorized_keys:
      - "{{ ssh_public_keys_dir }}/example_user.pub"
