---
mysql_packages:
  - mariadb-server-10.3
  - mariadb-client-10.3

mysql_bind_address: '0.0.0.0'

mysql_databases:
  - name: "{{ strapi_db_root }}{{ strapi_db_name }}"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "{{ strapi_db_root }}{{ strapi_db_user }}"
    host: "%"
    password: superSecretPassword
    priv: "{{ strapi_db_root }}{{ strapi_db_name }}.*:ALL"