---
# Global Node, NPM, Yarn vars
node_ver: 14.14.0

# Strapi application Vars
application_name: "my-strapi-app"
application_dir: "/srv/deploy/{{ application_name }}"
application_git: "https://github.com/derrickmehaffy/strapi-deploy-example"

# Nginx Vars
nginx_remove_default_vhost: false
nginx_upstream:
  - name: strapi
    strategy: "least_conn"
    servers: {
      "http://localhost:1337"
    }