---
# Global Node, NPM, Yarn vars
node_ver: 14.14.0
node_parent_install_dir: /usr/bin

# Strapi application Vars
# application_name: "my-strapi-app" # Set automatically by Terraform via ansible host_vars
application_dir: "/srv/deploy/{{ application_name }}"
application_git: "https://github.com/derrickmehaffy/strapi-deploy-example"

# ACME.sh vars
acme_sh_become_user: "root"
acme_sh_git_url: "https://github.com/acmesh-official/acme.sh"
acme_sh_git_version: "master"
acme_sh_upgrade: true
acme_sh_copy_certs_to_path: "/etc/nginx/ssl"
acme_sh_default_dns_provider: "dns_cf"
acme_sh_default_issue_renew_hook: "sudo systemctl reload nginx"
acme_sh_domains:
  - domains: ["{{ application_url }}"]

# Nginx Vars
nginx_remove_default_vhost: true
nginx_client_max_body_size: "256m"
nginx_upstreams:
  - name: strapi
    strategy: "least_conn"
    servers: { "localhost:1337" }
# Use if you are configuring with SSL
nginx_vhosts:
  - listen: "80"
    server_name: "{{ application_url }}"
    return: "301 https://{{ application_url }}$request_uri"
    filename: "{{ application_url }}.80.conf"
  - listen: "443 ssl"
    server_name: "{{ application_url }}.443.conf"
    ssl_cert: "{{ acme_sh_copy_certs_to_path }}/{{ application_url }}.pem"
    ssl_key: "{{ acme_sh_copy_certs_to_path }}/{{ application_url }}.key"
    upstream: "strapi"
    template: "../templates/nginx/strapi_ssl.conf.j2"
# Use if you are not using SSL
# nginx_vhosts:
#   - listen: "80"
#     server_name: "{{ application_url }}.80.conf"
#     upstream: "strapi"
#     template: "templates/nginx/strapi.conf.j2"

