---
- hosts: database
  become: true
  become_method: sudo
  remote_user: devops
  vars_files:
    - ../crypt_vars/database.yml

  roles:
    - role: mysql
      become: yes

- import_playbook: strapi_server.yml
