---
- hosts: strapi
  become: true
  become_method: sudo
  remote_user: devops
  vars_files:
    - ../crypt_vars/strapi.yml
    - ../crypt_vars/database.yml
    - ../tf_vars/tf_vars.yml

  roles:
    - role: nodejs
    - role: yarn
    - role: acme_sh
    - role: nginx

  tasks:
    - name: Create Strapi app directory for deploy user
      file:
        path: "{{ application_dir }}"
        state: directory
        owner: deploy
        group: deploy
        mode: 0775
    - name: Create app shared directory
      file:
        path: "{{ application_dir}}/shared"
        state: directory
        owner: deploy
        group: deploy
        mode: 0775

- import_playbook: strapi_dply.yml
