- name: Run Strapi service
  command: "pm2 startOrReload ecosystem.config.js -i max"
  args:
    chdir: "{{ application_dir }}/{{ ansistrano_current_dir }}"
  environment:
    NODE_ENV: production
- name: Save running pm2 services
  command: "pm2 save"
